
# Relative to root directory
siteconfig:
  deployFolder: './deploy'
  demosFolder: './demos'
  sourceFolder: './source'
  layoutsFolder: './layouts'
  browsers: ['opera', 'chrome', 'safari', 'firefox', 'ie']
  supportedBrowserClass: 'sd-browser-supported'
  panelCSS: 'panel.css'
  panelClass: 'sd-panel'
  panelTag: 'div'


# Allowed tags: js, forms, canvas, content, parser, svg, css, audio, video
demos:
  - slug: pagedcontent
    title: "Paged Content Magic"
    tags: [css]
    support: [opera]

  - slug: border-salon
    title: "Border Radius Salon"
    tags: [css, svg, parser]
    support: [opera, chrome, safari, firefox, ie]
    
  - slug: photobooth
    title: "Photobooth in Your browser"
    tags: [js, canvas]
    support: [opera, chrome]    
    
  - slug: parallax
    title: "Parallax Shifts"
    tags: [css]
    support: [opera, chrome, safari, firefox, ie]    

  - slug: keyboard
    title: "Type a key and hear a voice!"
    tags: [audio]
    support: [opera, chrome, safari, firefox, ie]    
    
  - slug: paranoid
    title: "Return of the Retro with a canvas game!"
    tags: [canvas]
    support: [opera, chrome, safari, firefox, ie]    
    
  - slug: object-fitness
    title: "Object Fit"
    tags: [css]
    support: [opera]  
    
  - slug: rock-piano
    title: "Rock Piano"
    tags: [css]
    support: [opera]
    
  - slug: tatami
    title: "Tatami"
    tags: [css]
    support: [opera]    
    
  - slug: isometric-city
    title: "An isometric world"
    tags: [css]
    support: [opera]   
    
  - slug: borderradius-fun
    title: "Tinkering with Border Radius"
    tags: [css]
    support: [opera, chrome, safari, firefox, ie]           