# Allowed tags: js, forms, canvas, content, parser, svg, css, audio, video

- slug: pagedcontent
  tags: [css]
  support: [opera, chrome, safari, firefox, ie]

- slug: css_br_extreme
  tags: [css, svg, parser]
  support: [opera, chrome, safari, firefox, ie]