
# Relative to root directory
siteconfig:
  deployFolder: './deploy'
  demosFolder: './demos'
  sourceFolder: './source'
  layoutsFolder: './layouts'
  browsers: ['opera', 'chrome', 'safari', 'firefox', 'ie']
  supportedBrowserClass: 'sd-browser-supported'
  panelCSS: 'panel.css'
  panelClass: 'sd-panel'
  panelTag: 'div'


# Allowed tags: js, forms, canvas, content, parser, svg, css, audio, video
demos:
  - slug: pagedcontent
    title: "Paged Content Magic"
    tags: [css]
    support: [opera]

  - slug: border-salon
    title: "Border Radius Salon"
    tags: [css, svg, parser]
    support: [opera, chrome, safari, firefox, ie]